Created & Linked Exercise & Demo Pages, Resolved #7 #8
codewit-us/codewit.us pull request #10
Opened 2024-03-03 17:34 UTC by numan-7

2024-03-06 02:20 UTC, KavetiRohith reviewed
LGTM

2024-03-06 02:20 UTC, KavetiRohith commented on codewit/lib/shared/validations/src/lib/demo.interfaces.ts
@numan-7 what's your opinion on moving the response interfaces to another lib instead of saving them here in the validations lib? 

Other than this the PR looks good to me.

2024-03-06 02:50 UTC, numan-7 commented on codewit/lib/shared/validations/src/lib/demo.interfaces.ts
You're absolutely correct, I made the appropriate changes. Thanks for pointing that out.

2024-03-06 03:10 UTC, KavetiRohith approved these changes

2024-03-06 04:12 UTC, KavetiRohith commented on codewit/tsconfig.base.json
> +      "@codewit/interfaces": ["interfaces/src/index.ts"],
just a small gripe can you move it to lib/shared/interfaces for consistency

2024-03-08 05:47 UTC, kbuffardi requested changes
After merging the backend changes, I tried re-building (via docker-compose) and launching it again. Some conflicts arose and I tried resolving them, but while build worked, launching caused these errors:

```
$ docker-compose up
[+] Running 3/0
 ✔ Container codewit-codewitus_db-1  Created                                                                                                           0.0s 
 ✔ Container codewit-app-1           Created                                                                                                           0.0s 
 ✔ Container codewit-frontend-1      Created                                                                                                           0.0s 
Attaching to app-1, codewitus_db-1, frontend-1
codewitus_db-1  | 
codewitus_db-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
codewitus_db-1  | 
codewitus_db-1  | 2024-03-08 05:41:46.515 UTC [1] LOG:  starting PostgreSQL 14.11 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 13.2.1_git20231014) 13.2.1 20231014, 64-bit
codewitus_db-1  | 2024-03-08 05:41:46.515 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
codewitus_db-1  | 2024-03-08 05:41:46.515 UTC [1] LOG:  listening on IPv6 address "::", port 5432
codewitus_db-1  | 2024-03-08 05:41:46.517 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
codewitus_db-1  | 2024-03-08 05:41:46.519 UTC [22] LOG:  database system was shut down at 2024-03-08 05:41:15 UTC
codewitus_db-1  | 2024-03-08 05:41:46.523 UTC [1] LOG:  database system is ready to accept connections
app-1           | 
app-1           | > @codewit/source@0.0.0 backend-dev
app-1           | > nx run api:serve:development
app-1           | 
frontend-1      | 
frontend-1      | > @codewit/source@0.0.0 frontend-dev
frontend-1      | > nx run client:serve:development --host 0.0.0.0 --port 3001
frontend-1      | 
app-1           | 
app-1           |  >  NX   The following projects are defined in multiple locations:
app-1           | 
app-1           |    - api: 
app-1           |      - api
app-1           |      - dist/api
app-1           |    
app-1           |    To fix this, set a unique name for each project in a project.json inside the project's root. If the project does not currently have a project.json, you can create one that contains only a name.
app-1           | 
app-1 exited with code 1
frontend-1      | node:events:496
frontend-1      |       throw er; // Unhandled 'error' event
frontend-1      |       ^
frontend-1      | 
frontend-1      | Error: listen EADDRINUSE: address already in use /tmp/4a84ff1227000ce6e564/fp18.sock
frontend-1      |     at Server.setupListenHandle [as _listen2] (node:net:1855:21)
frontend-1      |     at listenInCluster (node:net:1920:12)
frontend-1      |     at Server.listen (node:net:2025:5)
frontend-1      |     at /codewit/node_modules/nx/src/tasks-runner/psuedo-ipc.js:40:25
frontend-1      |     at new Promise (<anonymous>)
frontend-1      |     at PsuedoIPCServer.init (/codewit/node_modules/nx/src/tasks-runner/psuedo-ipc.js:32:16)
frontend-1      |     at ForkedProcessTaskRunner.init (/codewit/node_modules/nx/src/tasks-runner/forked-process-task-runner.js:31:30)
frontend-1      |     at TaskOrchestrator.run (/codewit/node_modules/nx/src/tasks-runner/task-orchestrator.js:37:44)
frontend-1      |     at runAllTasks (/codewit/node_modules/nx/src/tasks-runner/default-tasks-runner.js:27:25)
frontend-1      |     at defaultTasksRunner (/codewit/node_modules/nx/src/tasks-runner/default-tasks-runner.js:18:22)
frontend-1      | Emitted 'error' event on Server instance at:
frontend-1      |     at emitErrorNT (node:net:1899:8)
frontend-1      |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
frontend-1      |   code: 'EADDRINUSE',
frontend-1      |   errno: -98,
frontend-1      |   syscall: 'listen',
frontend-1      |   address: '/tmp/4a84ff1227000ce6e564/fp18.sock',
frontend-1      |   port: -1
frontend-1      | }
frontend-1      | 
frontend-1      | Node.js v20.11.1
app-1           | 
app-1           | > @codewit/source@0.0.0 backend-dev
app-1           | > nx run api:serve:development
app-1           | 
frontend-1 exited with code 0
frontend-1      | 
frontend-1      | > @codewit/source@0.0.0 frontend-dev
frontend-1      | > nx run client:serve:development --host 0.0.0.0 --port 3001
frontend-1      | 
app-1           | 
app-1           |  >  NX   The following projects are defined in multiple locations:
app-1           | 
app-1           |    - api: 
app-1           |      - api
app-1           |      - dist/api
app-1           |    
app-1           |    To fix this, set a unique name for each project in a project.json inside the project's root. If the project does not currently have a project.json, you can create one that contains only a name.
app-1           | 
app-1 exited with code 1
frontend-1      | 
frontend-1      | > nx run client:serve --host 0.0.0.0 --port 3001
frontend-1      | 
app-1           | 
app-1           | > @codewit/source@0.0.0 backend-dev
app-1           | > nx run api:serve:development
app-1           | 
frontend-1      | The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
app-1           | 
app-1           |  >  NX   The following projects are defined in multiple locations:
app-1           | 
app-1           |    - api: 
app-1           |      - api
app-1           |      - dist/api
app-1           |    
app-1           |    To fix this, set a unique name for each project in a project.json inside the project's root. If the project does not currently have a project.json, you can create one that contains only a name.
5:41:52 AM [vite] Internal server error: Failed to resolve import "../components/nav/Nav" from "src/app/app.tsx". Does the file exist?
frontend-1      |   Plugin: vite:import-analysis
frontend-1      |   File: /codewit/client/src/app/app.tsx:2:19
frontend-1      |   15 |    window.$RefreshSig$ = RefreshRuntime.createSignatureFunctionForTransform;
frontend-1      |   16 |  }
frontend-1      |   17 |  import NavBar from "../components/nav/Nav";
frontend-1      |      |                      ^
frontend-1      |   18 |  import Home from "../pages/Home";
frontend-1      |   19 |  import Read from "../pages/Read";
frontend-1      |       at formatError (file:///codewit/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:63768:46)
frontend-1      |       at TransformContext.error (file:///codewit/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:63762:19)
frontend-1      |       at normalizeUrl (file:///codewit/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:62037:33)
frontend-1      |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
frontend-1      |       at async file:///codewit/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:62191:47
frontend-1      |       at async Promise.all (index 3)
frontend-1      |       at async TransformContext.transform (file:///codewit/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:62112:13)
frontend-1      |       at async Object.transform (file:///codewit/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:64063:30)
frontend-1      |       at async loadAndTransform (file:///codewit/node_modules/vite/dist/node/chunks/dep-9A4-l-43.js:49741:29)
frontend-1      | 5:41:52 AM [vite] Pre-transform error: Failed to resolve import "../components/nav/Nav" from "src/app/app.tsx". Does the file exist?
frontend-1      | 5:41:52 AM [vite] Pre-transform error: Failed to resolve import "../components/error/Error" from "src/pages/ExerciseForms.tsx". Does the file exist?
frontend-1      | 5:41:52 AM [vite] Pre-transform error: Failed to resolve import "../components/form_demo/VideoSelect" from "src/pages/DemoForms.tsx". Does the file exist?
frontend-1      | 5:41:52 AM [vite] Pre-transform error: Failed to r [...]

2024-03-09 06:05 UTC, kbuffardi approved these changes
LGTM

2024-03-09 06:06 UTC, merged