Refactor Code
codewit-us/codewit.us pull request #36
Opened 2024-10-08 00:40 UTC by numan-7

- Refactored and streamlined API logic by moving more functionality into custom hooks.
- Restructured hooks to follow a consistent and scalable pattern.
- Implemented missing TypeScript models.
- Cleaned up some form logic.
- Added some missing loading and error page redirects.

2024-10-21 18:17 UTC, Tony-Ton3 requested changes
Create and Manage Users Links under Nav.tsx should be hidden when user is NOT an admin.

2024-10-21 19:26 UTC, Tony-Ton3 approved these changes
lgtm

2024-10-28 23:56 UTC, rkaveti-uptycs approved these changes

2024-10-28 23:58 UTC, KavetiRohith approved these changes

2024-10-28 23:59 UTC, merged