Setup Styling & Images
codewit-us/codewit.us pull request #6
Opened 2024-02-13 19:17 UTC by numan-7

- Configured Tailwind Config File & Imported Design Images
- Just added small small subheadings under Frontend Roadmap on where to find the changes just for future reference.

2024-02-14 23:21 UTC, kbuffardi requested changes
Just a couple minor revisions.

2024-02-14 23:21 UTC, kbuffardi commented on codewit/client/index.html
> +    <title>Codewit.us</title>
Let's stick with branding that's consistent with the (all lowercase) logo: `codewit.us`

2024-02-14 23:21 UTC, kbuffardi commented on ROADMAP.md
> +- The site icon, or favicon, which appears in the browser tab, is located under the `codewit/client/public/` directory alongside the logo and hexicon. The icon is currently initialized in `codewit/cl
These descriptions are fine, although let's cut out the last sentence. Pretty soon we'll develop a header bar and the favicon will probably "live" there.

2024-02-14 23:41 UTC, numan-7 commented
> Just a couple minor revisions.

Resolved both of them.

2024-02-20 03:12 UTC, kbuffardi approved these changes

2024-02-20 03:12 UTC, merged